name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DEB: pandoc-3.1.4-1-amd64.deb
  PANDOC_DEB: https://github.com/jgm/pandoc/releases/download/3.1.4/pandoc-3.1.4-1-amd64.deb

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Verification
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose
    - run: wget $PANDOC_DEB
    - run: sudo dpkg -i $DEB
    - name: Run tests
      run: cargo test --verbose
